
    function MyFunction(){
        let arr = [Math.random(), Math.random(), Math.random()];
        //find the smallest element in 'arr'. 
        smallest = arr[0];
     
        for(var i = 1; i < 3; ++i){
            if (smallest > arr[i])
                smallest = arr[i];
        }
        document.getElementById("demo").innerHTML = 
         "A set of three random numbers generated by the computer. <br/> The numbers are <br/>" + arr[0] + "<br/>" 
                + arr[1]+ "</br>" + arr[2] + "<br/>"+ "The smallest of these numbers is " + smallest;
        //find a random number between 0 and 10
        //Math.floor rounds a number to the nearest integer
        //modulus ( % in x % y) returns the remainder when x is divided by y
        // so, for example,   100 % 3 is 1, 10 % 2 is 0 and so on
        document.getElementById("demo2").innerHTML = 
        "A random number between 0 and 10 is " + Math.floor(100 *Math.random()) % 11;
    }